language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - cd code ; npm install --only=dev ; cd ..
script:
    - cd code ; platformio run -e itead-sonoff-basic
branches:
    only:
        - master
        - dev
